name: geostat
channels:
    - defaults
dependencies:
    - python=3.7
    - pandas
    - scipy
    - matplotlib
    - jupyter
    - bokeh=1.4.0
    - plotly
    - holoviews
    - pip:
        - jupyter_contrib_nbextensions
        - rise==5.6.1