# This is a basic workflow to compile and deploy notebook-classroom

name: Notebook-Classrom

# Only run on push to the master branch
on: 
  push:
    branches: [ master, patch-exercises ]
  schedule:
    # change this as you need it: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    # runs at 1:30 on saturday
    - cron: '30 1 * * 6'

# Jobs to compile notebook classroom
jobs:
  # Publish the application on github pages
  publish:
    # use ubuntu
    runs-on: ubuntu-18.04

    steps:
    # Checks-out  $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Conda
      uses: s-weigand/setup-conda@v1.0.2
      with:
        python-version: 3.6

    # install requirements
    - name: Install requirements
      run: | 
        conda env update -f environment.yml -n base
        
    # Compile notebooks
    - name: Compile Notebooks
      run: | 
        cd ./lectures
        mkdir ./nb
        jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 --output-dir='./nb' *.ipynb
        jupyter nbconvert --to slides --execute --ExecutePreprocessor.timeout=120 --output-dir='./nb' *ipynb
    
    # install latest notebook classroom app
    - name: Install Notebook-classroom
      run: | 
        cd ./lectures
        wget https://github.com/hydrocode-de/notebook-classroom/releases/latest/download/notebook-classroom.zip
        unzip ./notebook-classroom.zip -d ./dist
    
    # move all neccessary files
    - name: Copy content
      run: | 
        cd ./lectures
        mv ./nb/* ./dist/nb
        mv configuration.js ./dist/configuration.js
        [ -d ./static ] && mv ./static/* ./dist/static/* 
        [ -f ./index.md ] && mv index.md ./dist/static/index.md
        # append the date to index.md
        python -c "from datetime import datetime as dt;print('\n## Last Update\n\n  %s\n' % dt.now())" >> ./dist/static/index.md

    # copy the exercises
    # TODO: maybe add all readme files
    - name: Add Exercises
      run: |
        mv ./exercises/README.md ./lectures/dist/static/exercises.md
        zip -r ./lectures/dist/static/exercises.zip ./exercises
    
    # add Project files
#    - name: Add Project files
#      run: mv ./projects/* ./lectures/dist/static/*

        
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: ./lectures/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
